### ISSUE TITLE
Needs Privacy Policy for Antimicro

### ISSUE THREAD

**Issue by mayrinck** [mayrinck/FOSSonMicrosoftStore#6]
Does anyone have the link for Antimicro's privacy policy page or document?

**Comment by Joshagos** [comment]
I don't think they have a privacy policy. The closest thing I could find was their license: http://www.gnu.org/licenses/gpl.txt

**Comment by mayrinck** [comment]
> 
> 
> I don't think they have a privacy policy. The closest thing I could find was their license: http://www.gnu.org/licenses/gpl.txt

I will try with this one and see what happens, I've also tried to get in touch with the devs to ask for a Privacy Policy document or something we could use but it seems they really don't have any...

**Comment by mayrinck** [comment]
> 
> 
> > I don't think they have a privacy policy. The closest thing I could find was their license: http://www.gnu.org/licenses/gpl.txt
> 
> I will try with this one and see what happens, I've also tried to get in touch with the devs to ask for a Privacy Policy document or something we could use but it seems they really don't have any...

This didn't work... I really don't kwno why a software like Antimicro would need to have a Privacy Policy if it doesn't actually grab any data form the user except controller imputs but... "Microsoft Rules" and Reviewers say so...

**Comment by mayrinck** [comment]
Well, considering the info given by the devs on their own repository, I could create a [file to represent the privacy policy](https://github.com/mayrinck/FOSSonMicrosoftStore/blob/main/SoftwareIndex/antimicro/antimicro-privacy-policy.md) for Antimicro, so now it is available on Microsoft Store! Yay!
